behaviors:
  GridFoodCollector:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.90
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 50000

  ControllerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.90
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 2000000
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 100000